const products = [
  {
    _id: '1',
    name: 'Poop And Pee Odou...',
    longname: 'Poop And Pee Odour Eliminator',
    image: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-deo1-8dd-320x320.jpg',
    imageLong: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-deo1-8dd.jpg',
    description:
      'Cizar Care Poop & Pee Odor eliminator utilizes its unique enzyme blend for eliminating the unpleasant smell and stains caused by waste. It consists of 100% natural and organic ingredients, ensuring a safe and environmentally friendly solution. Finally, bid farewell to any unpleasant odor in your home and enjoy a stain-free environment for you and your furry friend.',
    brand: '',
    category: 'Pet Care', 
    delprice: 1195.00,
    price: 693,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Herbal Pet Deodorizer',
    longname: 'Herbal Pet Deodorizer',
    image: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-herbal1-66f-320x320.jpg',
    imageLong: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-herbal1-66f.jpg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti deserunt, praesentium, amet cum omnis doloribus, possimus id ut dolorem voluptatum perspiciatis libero.',
    brand: '',
    category: '',
    price: 693.99,
    delprice: 1195.00,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Tap And Tile Cleaner',
    longname: 'Tap And Tile Cleaner',
    image: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-tap2-851-320x320.jpg',
    imageLong: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-tap2-851.jpg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti deserunt, praesentium, amet cum omnis doloribus, possimus id ut dolorem voluptatum perspiciatis libero.',
    brand: 'Cannon',
    category: 'Electronics',
    price: 345,
    delprice: 595,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'All In One Detergent...',
    longname: 'All In One Detergent With Enzyme',
    image: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-ditee1-77e-600x600.jpg',
    imageLong: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-ditee1-77e.jpg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti deserunt, praesentium, amet cum omnis doloribus, possimus id ut dolorem voluptatum perspiciatis libero.',
    brand: '',
    category: '',
    price: 345.00,
    delprice: 595.00,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Dish Wash With Enzyme',
    longname: 'Dish Wash With Enzyme',
    image: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-dish1-4c0-320x320.jpg',
    imageLong: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-dish1-4c0.jpg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti deserunt, praesentium, amet cum omnis doloribus, possimus id ut dolorem voluptatum perspiciatis libero.',
    brand: '',
    category: '',
    price: 345.00,
    delprice: 595.00,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Multi Purpose Cleanse....',
    longname: 'Multi Purpose Cleaner With Enzyme',
    image: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-multi1-2d7-320x320.jpg',
    imageLong: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-multi1-2d7.jpg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti deserunt, praesentium, amet cum omnis doloribus, possimus id ut dolorem voluptatum perspiciatis libero.',
    brand: '',
    category: '',
    price: 345.00,
    delprice: 595.00,
    countInStock: 4,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Toilet Bowl Cleanse...',
    longname: 'Toilet Bowl Cleanser With Enzyme',
    image: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-too3-ba7-320x320.jpg',
    imageLong: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-too3-ba7.jpg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti deserunt, praesentium, amet cum omnis doloribus, possimus id ut dolorem voluptatum perspiciatis libero.',
    brand: '',
    category: '',
    price: 345.00,
    delprice: 595.00,
    countInStock: 4,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Care Bio Septic',
    longname: 'Care Bio Septic',
    image: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-bio-2-62b-320x320.jpg',
    imageLong: 'https://cizar.in/wp-content/uploads/2024/02/cizar-hygiene-care-pvt-ltd-bio-2-62b.jpg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti deserunt, praesentium, amet cum omnis doloribus, possimus id ut dolorem voluptatum perspiciatis libero.',
    brand: '',
    category: '',
    price: 1288.00,
    delprice: 2200.00,
    countInStock: 4,
    rating: 4,
    numReviews: 12,
  }
]

module.exports = products;
